name: Push to GitHub

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Push changes
        run: |
          git remote add target https://github.com/Louaq/hugo.git
          git push target HEAD:refs/heads/main
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
 
