name: Push to Another Repository

# 
on:
 push:
   branches:
     - main

jobs:
 build:
   runs-on: ubuntu-latest

   steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Push to another repository
       env:
         ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
       run: |
         git remote add target https://$ACCESS_TOKEN@github.com/Louaq/hugo.git
         git push target HEAD:refs/heads/main 
